flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- StateVar-1.1.0.1
- adjunctions-4.2.2
- aeson-0.10.0.0
- asn1-encoding-0.9.3
- asn1-parse-0.9.4
- asn1-types-0.3.1
- async-2.0.2
- attoparsec-0.13.0.1
- base-orphans-0.4.4
- base64-bytestring-1.0.0.1
- bifunctors-5.1
- blaze-builder-0.4.0.1
- byteable-0.1.1
- case-insensitive-1.2.0.5
- cereal-0.5.1.0
- comonad-4.2.7.2
- conduit-1.2.6
- connection-0.2.5
- contravariant-1.3.3
- cookie-0.4.1.6
- cryptonite-0.9
- data-default-class-0.0.1
- distributive-0.4.4
- dlist-0.7.1.2
- exceptions-0.8.0.2
- free-4.12.1
- hashable-1.2.3.3
- hourglass-0.2.9
- http-client-0.4.25
- http-client-tls-0.2.2
- http-conduit-2.1.8
- http-types-0.9
- kan-extensions-4.2.3
- lens-4.13
- lens-aeson-1.0.0.5
- lifted-base-0.2.3.6
- memory-0.10
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- parallel-3.2.0.6
- parsec-3.1.9
- pem-0.2.2
- prelude-extras-0.4.0.2
- primitive-0.6.1.0
- profunctors-5.1.2
- random-1.1
- reflection-2.1
- resourcet-1.1.7
- scientific-0.3.4.4
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- socks-0.5.4
- stm-2.4.4
- streaming-commons-0.1.15
- syb-0.6
- tagged-0.8.2
- text-1.2.1.3
- tls-1.3.3
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- vector-0.11.0.0
- void-0.7.1
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.1
- x509-validation-1.6.3
- zlib-0.6.1.1
resolver: ghc-7.10
